#common
## button / label
jp.ecuacion.splib.web.common.button.insert.default=new
jp.ecuacion.splib.web.common.button.update.default=edit
jp.ecuacion.splib.web.common.button.delete.default=delete
jp.ecuacion.splib.web.common.button.search.default=search
jp.ecuacion.splib.web.common.button.back.default=back
jp.ecuacion.splib.web.common.button.conditionClear.default=clear
jp.ecuacion.splib.web.common.button.download.default=download
jp.ecuacion.splib.web.common.label.submitOnChangeToRefresh.default= (reload on change)
jp.ecuacion.splib.web.common.label.recordsInScreen.default=displayed results
jp.ecuacion.splib.web.common.label.searchPattern.exactMatch.default=(exact match)
jp.ecuacion.splib.web.common.label.searchPattern.partialMatch.default=(partial match)
jp.ecuacion.splib.web.common.label.searchPattern.prefixMatch.default=(prefix match)
jp.ecuacion.splib.web.common.label.searchPattern.postfixMatch.default=(postfix match)
jp.ecuacion.splib.web.common.label.prev.default=Previous
jp.ecuacion.splib.web.common.label.next.default=Next
jp.ecuacion.splib.web.common.label.submitting.default=submitting...

## input
jp.ecuacion.splib.web.components.inputTakenPhoto.registeredPhoto=(registered photo)
jp.ecuacion.splib.web.components.inputTakenPhotoPc.photoShootingButtonLabel=photo shooting
jp.ecuacion.splib.web.components.inputTakenPhotoPc.shootButtonLabel=shoot
jp.ecuacion.splib.web.components.inputTakenPhotoPc.reshootButtonLabel=shoot again

## switchUser
jp.ecuacion.splib.web.switchUser.switchButton.default=Switch User

# config
config.appVersion=app version
config.excelTemplateVersion=excel template version
config.codeGeneratorVersion=code generator version

# login
login.username.default=ID (e-mail address)
login.password.default=password
adminLogin.username.default=ID (e-mail address)
adminLogin.password.default=password
